config/routes.rb
Rails.application.routes.draw do
  get 'blogs/index'
  get 'blogs', to: 'blogs#index'
  get 'blogs/:page', to: 'blogs#index'

  get 'blogs/genre/:id', to: 'blogs#genre'
  get 'blogs/genre/:id/:page', to: 'blogs#genre'

  get 'blogs/show/:id', to: 'blogs#show'

  get 'blogposts/index'
  get 'blogposts', to: 'blogposts#index'

  get 'blogposts/delete/:id', to: 'blogposts#delete'
  post 'blogposts/delete', to: 'blogposts#delete'
  post 'blogposts/delete/:id', to: 'blogposts#delete'

  get 'blogposts/add'
  post 'blogposts/add'

  get 'blogposts/:id', to: 'blogposts#edit'
  patch 'blogposts/:id', to: 'blogposts#edit'

  get 'blogposts/delete'
  
  get 'bloggenres/indeex'
  get 'bloggenres' , to: 'bloggenres#indeex'

  get 'bloggenres/add'
  post 'bloggenres/add'

  get 'bloggenres/:id', to: 'bloggenres#edit'
  patch 'bloggenres/:id', to: 'bloggenres#edit'

  get 'blogconfigs/index'
  get 'blogconfigs', to: 'blogconfigs#index'

  get 'blogconfigs/edit'
  patch 'blogconfigs/edit'

  resources :board_messages
  resources :board_users
  resources :data_pages
  get 'hello/index'
  get 'hello/login_check'
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogconfig.rb
class Blogconfig < ApplicationRecord
	validates :title, :stylename, presence: {message:'は、必須項目です。'}
end

app/models/bloggenre.rb
class Bloggenre < ApplicationRecord
	has_many :blogpost
	
	validates :name, presence: {message:'は、必須項目です。'}
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
	belongs_to :bloggenre
	has_rich_text :content

	validates :title, :content, presence: {message:'は、必須項目です。'}
end

app/models/board_message.rb
class BoardMessage < ApplicationRecord
  belongs_to :board_user

  validates :content, presence: {message:'は、必須科目です。'}
end

app/models/board_user.rb
class BoardUser < ApplicationRecord
	belongs_to :account
	has_many :board_message

	validates :nickname, presence: {message: 'は、必須科目です。'}
end

app/models/data_page.rb
class DataPage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bloggenres_controller.rb
class BloggenresController < ApplicationController
  layout 'blog'

  def indeex
    @data = Bloggenre.all
  end

  def add
    @bloggenre = Bloggenre.new
    if request.post? then
      @bloggenre = Bloggenre.create bloggenre_params
      redirect_to '/bloggenres'
    end
  end

  def edit
    @bloggenre = Bloggenre.find(params[:id])
    if request.patch? then
      @bloggenre.update bloggenre_params
      redirect_to '/bloggenres'
    end
  end

  private
  def bloggenre_params
    params.require(:bloggenre).permit(:name, :memo)
  end

end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  layout 'blog'

  def index
    @data = Blogpost.all.order('created_at desc')
  end

  def add
    @blogpost = Blogpost.new
    @genres = Bloggenre.all
    if request.post? then
      @blogpost = Blogpost.create blogposts_params
      redirect_to '/blogposts'
    end
  end

  def edit
    @blogpost = Blogpost.find(params[:id])
    @genres = Bloggenre.all
    if request.patch? then
      @blogpost.update blogposts_params
      redirect_to '/blogposts'
    end
  end

  def delete
    @blogpost = Blogpost.find(params[:id])
    if request.post? then
      @blogpost.destroy
      redirect_to '/blogposts'
    end
  end

  private
  def blogposts_params
    params.require(:blogpost).permit(:title, :read, :content, :bloggenre_id)
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  layout 'blogs'

  def index
    @data = Blogpost.order('created_at desc').page params[:page]
    @blogconfig = Blogconfig.find 1
  end

  def genre
    @genre = Bloggenre.find params[:id]
    @data = Blogpost.where('bloggenre_id = ?',params[:id]).order('created_at desc').page params[:page]
    @blogconfig = Blogconfig.find 1
  end

  def show
    @blogpost = Blogpost.find params[:id]
    @blogconfig = Blogconfig.find 1
  end
  
end

app/controllers/data_pages_controller.rb
class DataPagesController < ApplicationController
  before_action :set_data_page, only: [:show, :edit, :update, :destroy]

  # GET /data_pages
  # GET /data_pages.json
  def index
    @data_pages = DataPage.page params[:page]
  end

  # GET /data_pages/1
  # GET /data_pages/1.json
  def show
  end

  # GET /data_pages/new
  def new
    @data_page = DataPage.new
  end

  # GET /data_pages/1/edit
  def edit
  end

  # POST /data_pages
  # POST /data_pages.json
  def create
    @data_page = DataPage.new(data_page_params)

    respond_to do |format|
      if @data_page.save
        format.html { redirect_to @data_page, notice: 'Data page was successfully created.' }
        format.json { render :show, status: :created, location: @data_page }
      else
        format.html { render :new }
        format.json { render json: @data_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_pages/1
  # PATCH/PUT /data_pages/1.json
  def update
    respond_to do |format|
      if @data_page.update(data_page_params)
        format.html { redirect_to @data_page, notice: 'Data page was successfully updated.' }
        format.json { render :show, status: :ok, location: @data_page }
      else
        format.html { render :edit }
        format.json { render json: @data_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_pages/1
  # DELETE /data_pages/1.json
  def destroy
    @data_page.destroy
    respond_to do |format|
      format.html { redirect_to data_pages_url, notice: 'Data page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_data_page
      @data_page = DataPage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def data_page_params
      params.require(:data_page).permit(:data)
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  layout 'application'
  before_action :authenticate_account!, only: :login_check

  def index
    @msg = 'this is sample page.'
  end

  def login_check
    @account = current_account
    @msg = 'account created at: ' + @account.created_at.to_s
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogconfigs_helper.rb
module BlogconfigsHelper
end

app/helpers/bloggenres_helper.rb
module BloggenresHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/board_messages_helper.rb
module BoardMessagesHelper
end

app/helpers/board_users_helper.rb
module BoardUsersHelper
end

app/helpers/data_pages_helper.rb
module DataPagesHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/views/bloggenres/add.html.erb
<h1 class="display-4 text-primary">Bloggenres#add</h1>
<p>※ジャンル・データの作成</p>
<% if @bloggenre.errors.any? %>
<ul>
	<% @bloggenre.errors.full_messages.each do |err| %>
		<li><%= err %></li>
	<% end %>
</ul>
<% end %>
<%= form_for(@bloggenre, url:{controller:'bloggenres', action:'add'}) do |form| %>
<div class="form-group">
	<label for="name">Name</label>
	<%= form.text_field :name,{class:"form-control"} %>
</div>
<div class="form-group">
	<label for="memo">Memo</label>
	<%= form.text_field :memo,{class:"form-control"} %>
</div>
<td><%= form.submit "作成" %></td></tr>
<% end %>

app/views/bloggenres/edit.html.erb
<h1 class="display-4 text-primary">Bloggenres#edit</h1>
<p>※「<%= @bloggenre.name %>」ジャンルの編集</p>
<% if @bloggenre.errors.any? %>
<ul>
	<% @bloggenre.errors.full_messages.each do |err| %>
		<li><%= err %></li>
	<% end %>
</ul>
<% end %>
<%= form_for(@bloggenre, url:{controller:'bloggenres', action:'edit'}) do |form| %>
<div class="form-group">
	<label for="name">Name</label>
	<%= form.text_field :name,{class:"form-control"} %>
</div>
<div class="form-group">
	<label for="memo">Memo</label>
	<%= form.text_field :memo,{class:"form-control"} %>
</div>
<td><%= form.submit "更新" %></td></tr>
<% end %>

app/views/bloggenres/indeex.html.erb
<h1 class="display-4 text-primary">Bloggenres#indeex</h1>
<p>※ジャンル・データの一覧</p>
<table class="table">
	<tr>
		<th>Id</th><th>name</th><th>memo</th><th></th>
	</tr>
	<% @data.each do |obj| %>
	<tr>
		<td><%= obj.id %></td>
		<td><%= obj.name %></td>
		<td><%= obj.memo %></td>
		<td><a href="/bloggenres/<%= obj.id %>">Edit</a></td>
	</tr>
	<% end %>
</table>
<p><a href="/bloggenres/add">新規作成＞＞</a></p>

app/views/blogposts/add.html.erb
<h1 class="display-4 text-primary">Blogposts#add</h1>
<p>※ブログ記事の投稿</p>
<% if @blogpost.errors.any? %>
<ul>
	<% @blogpost.errors.full_messages.each do |err| %>
		<li><%= err %></li>
	<% end %>
</ul>
<% end %>

<%= form_for(@blogpost, url:{controller:'blogposts', action:'add'}) do |form| %>
<div class="form-group">
	<label for="title">Title</label>
	<%= form.text_field :title,{class:"form-control"} %>
</div>
<div class="form-group">
	<label for="read">Read</label>
	<%= form.text_field :read,{class:"form-control"} %>
</div>
<div class="form-group">
	<label for="content">Content</label>
	<%= form.rich_text_area :content %>
</div>
<div class="form-group">
	<label for="bloggenre_id">Genre IO</label>
	<%= form.text_field :bloggenre_id,{class:"form-control"} %>
</div>
<%= form.submit "作成" %>
<% end %>

<h5 class="mt-4 text-primary">※ジャンルの一覧</h5>
<table class="table">
	<tr>
		<th>Id</th><th>Genre</th>
	</tr>
	<% @genres.each do |obj| %>
	<tr>
		<td><%= obj.id %></td>
		<td><%= obj.name %></td>
	</tr>
	<% end %>
</table>

app/views/blogposts/delete.html.erb
<h1 class="display-4 text-primary">Blogposts#delete</h1>
<p>※以下を削除してもいいですか？</p>
<table class="table">
	<tr><th>Id</th>
		<td><%= @blogpost.id %></td></tr>
	<tr><th>title</th>
		<td><%= @blogpost.title %></td></tr>
	<tr><th>read</th>
		<td><%= @blogpost.read %></td></tr>
	<tr><th>content</th>
		<td><%= @blogpost.content %></td></tr>
</table>
<%= form_tag controller: "blogposts", action: "delete" do %>
<%= hidden_field_tag "id", {value: @blogpost.id} %>
<%= submit_tag "削除" %>
<% end %>

app/views/blogposts/edit.html.erb
<h1 class="display-4 text-primary">Blogposts#edit</h1>
<p>※「<%= @blogpost.title %>」の編集</p>
<% if @blogpost.errors.any? %>
<ul>
	<% @blogpost.errors.full_messages.each do |err| %>
		<li><%= err %></li>
	<% end %>
</ul>
<% end %>
<%= form_for(@blogpost, url:{controller:'blogposts', action:'edit'}) do |form| %>
<div class="form-group">
	<label for="title">Title</label>
	<%= form.text_field :title,{class:"form-control"} %>
</div>
<div class="form-group">
	<label for="read">Read</label>
	<%= form.text_field :read,{class:"form-control"} %>
</div>
<div class="form-group">
	<label for="content">Content</label>
	<%= form.rich_text_area :content %>
</div>
<div class="form-group">
	<label for="bloggenre_id">Genre ID</label>
	<%= form.text_field :bloggenre_id,{class:"form-control"} %>
</div>
<td><%= form.submit "更新" %></td></tr>
<% end %>

<h5 class="mt-4 text-primary">※ジャンルの一覧</h5>
<table class="table">
	<tr>
		<th>Id</th><th>Genre</th>
	</tr>
	<% @genres.each do |obj| %>
	<tr>
		<td><%= obj.id %></td>
		<td><%= obj.name %></td>
	</tr>
	<% end %>
</table>

app/views/blogposts/index.html.erb
<h1 class="display-4 text-primary">Blogposts#index！</h1>
<p>※投稿記事の一覧</p>
<table class="table">
	<tr>
		<th>Id</th><th>title</th><th>read</th><th>genre</th><th colspan="2"></th>
	</tr>
	<% @data.each do |obj| %>
	<tr>
		<td><%= obj.id %></td>
		<td><%= obj.title %></td>
		<td><%= obj.read %></td>
		<td><%= obj.bloggenre.name %></td>
		<td><a href="/brogposts/<%= obj.id %>">Edit</a></td>
		<td><a href="/brogposts/delete/<%= obj.id %>">Delete</a></td>
	</tr>
	<% end %>
</table>
<p><a href="/blogposts/add">新規作成＞＞</a></p>

app/views/data_pages/_form.html.erb
<%= form_with(model: data_page, local: true) do |form| %>
  <% if data_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(data_page.errors.count, "error") %> prohibited this data_page from being saved:</h2>

      <ul>
        <% data_page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_area :data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/data_pages/edit.html.erb
<h1>Editing Data Page</h1>

<%= render 'form', data_page: @data_page %>

<%= link_to 'Show', @data_page %> |
<%= link_to 'Back', data_pages_path %>

app/views/data_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-4 text-primary" >Data Pages</h1>

<div class="mt-4 mb-4">
  <%= page_entries_info @data_pages %>
</div>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Data</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_pages.each do |data_page| %>
      <tr>
        <td><%= data_page.id %></td>
        <td><%= data_page.data %></td>
        <td><%= data_page.created_at %></td>
        <td><%= link_to 'Show', data_page %></td>
        <td><%= link_to 'Edit', edit_data_page_path(data_page) %></td>
        <td><%= link_to 'Destroy', data_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div><%= paginate @data_pages %></div>
<br>

<%= link_to 'New Data Page', new_data_page_path %>

app/views/data_pages/new.html.erb
<h1>New Data Page</h1>

<%= render 'form', data_page: @data_page %>

<%= link_to 'Back', data_pages_path %>

app/views/data_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @data_page.data %>
</p>

<%= link_to 'Edit', edit_data_page_path(@data_page) %> |
<%= link_to 'Back', data_pages_path %>